# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "News"
  url = "#news"
  weight = 2

[[main]]
  name = "Researches"
  url = "#researches"
  weight = 3

[[main]]
  name = "Publications"
  url = "#publications_featured"
  weight = 4

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 5

[[main]]
  name = "Resources"
  url = "#resources"
  weight = 6

[[main]]
  name = "Services"
  url = "#services"
  weight = 7

[[main]]
  name = "Awards"
  url = "#awards"
  weight = 8

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 9

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 10
