baseurl = "http://home.ustc.edu.cn/~dongzhi/"  # End your URL with a `/` trailing slash.
title = "Dongdong Tian"
copyright = "&copy; 2012-2017 Dongdong Tian"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "Dongdong Tian"
  role = "PhD Candidate in Geophysics"
  organization = "University of Science and Technology of China"
  organization_url = "http://en.ustc.edu.cn/"
  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "portrait.jpg"
  email = "dongzhi@mail.ustc.edu.cn"
  address = "No.96, JinZhai Road Baohe District, Hefei, Anhui, 230026, China."
  office_hours = ""
  phone = "+86-15055117035"
  skype = ""
  telegram = ""

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   highlight_version
  #     Choose the version of highlight.js you want. Setting this
  #     option in a page's preamble has no effect.
  #
  #     Example: highlight_version = "9.9.0"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = false
  highlight_languages = []
  # highlight_style = "github"
  # highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "orcid"
    icon_pack = "ai"
    link = "http://orcid.org/0000-0001-7967-1197"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=VITag6sAAAAJ"

  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "https://www.researchgate.net/profile/Dongdong_Tian"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/seisman"

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:dongzhi@mail.ustc.edu.cn"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 2

[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Software"
  url = "#software"
  weight = 5

[[menu.main]]
  name = "Links"
  url = "#links"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"

# Configure the Chinese version of the website.
[languages.zh]
  languageCode = "zh-cn"

#[languages.zh.params]
# see https://github.com/gcushen/hugo-academic/issues/213
  name = "田冬冬"
  role = "地球物理学在读博士生"
  organization = "中国科学技术大学"
  organization_url = "http://www.ustc.edu.cn/"
  address = "安徽省合肥市中国科学技术大学"

  publication_types = [
    '未分类',  # 0
    '会议论文集',  # 1
    '期刊论文',  # 2
    '待发表论文',  # 3
    '技术报告',  # 4
    '书籍',  # 5
    '书籍章节'  # 6
  ]

[[languages.zh.menu.main]]
  name = "首页"
  url = "#about"
  weight = 1

[[languages.zh.menu.main]]
  name = "文章"
  url = "#publications_selected"
  weight = 2

[[languages.zh.menu.main]]
  name = "报告"
  url = "#talks"
  weight = 3

[[languages.zh.menu.main]]
  name = "项目"
  url = "#projects"
  weight = 4

[[languages.zh.menu.main]]
  name = "软件"
  url = "#software"
  weight = 5

[[languages.zh.menu.main]]
  name = "链接"
  url = "#links"
  weight = 6

[[languages.zh.menu.main]]
  name = "联系方式"
  url = "#contact"
  weight = 7
