# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://msu.edu/~tiandong/"

# Title of your site
title = "Dongdong Tian"

# Your copyright notice - appears in site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; 2012 - 2018 Dongdong Tian"

theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10
disablePathToLower = true

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = true # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

# Get last modified date for content from Git?
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).
  extensions = ["backslashLineBreak"]

[params]
  # AUTHOR SETUP

  # Your details.
  name = "Dongdong Tian"
  role = "Postdoctoral Research Associate"

  # Organizations/Affiliations.
  #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
  organizations = [ { name = "Michigan State University", url = "https://msu.edu/" } ]

  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "portrait.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.

  # Details for the Contact Widget
  email = "tiandong@msu.edu"
  address = "Natural Science Building, 288 Farm Lane, Room 313, East Lansing, MI 48824, USA"
  office_hours = ""
  phone = "+1 517 775 1438"
  skype = ""
  telegram = ""
  keybase = ""  # Your keybase.io username.

  # Enter an optional link for booking appointments (e.g. calendly.com).
  appointment_url = ""

  # Discussion link (e.g. link to a forum, mailing list, or chat).
  #   Uncomment line below to use.
  #   discussion = { name = "Discuss", url = "https://discourse.gohugo.io" }

  # Enable/disable map in Contact widget.
  # To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
  # a map provider below.
  # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `map = 2`.
  # To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  # To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  map = 1
  map_api_key = "AIzaSyBP5DIVloAvKk7NCjV2NzvsH7wLa5BB2Pw"
  latitude = "42.731066"
  longitude = "-84.477028"
  zoom = 15

  # SITE SETUP

  # Color theme.
  #   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`.
  color_theme = "default"
  # Enable users to switch between day and night mode?
  day_night = true

  # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "default"

  # Description for social sharing and search engines. If undefined, author role is used in place.
  description = ""

  # Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
  sharing_image = ""

  # Twitter username (without @). Used when a vistor shares your site on Twitter.
  twitter = ""

  # Diplay a logo in navigation bar rather than title (optional).
  #   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
  logo = ""

  # Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "3:04 PM"

  # Show estimated reading time for posts?
  reading_time = false

  # Display comment count? Requires commenting to be enabled.
  comment_count = true

  # Display next/previous section pager?
  section_pager = false

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   For the list of supported languages and styles, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = []
  # highlight_style = "github"

  # Enable native social sharing buttons?
  sharing = false

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ['custom.css']
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multilingual sites, `publication_types` can be copied to each language section at the end of this file and
  #   translated.
  publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section'  # 6
  ]

  # Configuration of talk pages.
  [params.talks]
    # Show talk time?
    time = true

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true

    # Post list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = Stream
    post_format = 2

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    #   4 = Stream
    publication_format = 3

    # Talk list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = Stream
    talk_format = 0

  # Social/Academic Networking
  #
  # Icon pack "fab" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fas" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fontawesome.com/icons
  #
  # Icon pack "ai" includes the following academic icons:
  #
  #   cv, google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "orcid"
    icon_pack = "ai"
    link = "http://orcid.org/0000-0001-7967-1197"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=VITag6sAAAAJ"

  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "https://www.researchgate.net/profile/Dongdong_Tian"

  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "https://github.com/seisman"

  [[params.social]]
    icon = "globe"
    icon_pack = "fas"
    link = "https://seisman.info/"

  [[params.social]]
    icon = "envelope"
    icon_pack = "fas"
    link = "mailto:tiandong@msu.edu"

  # Link to a PDF of your resume/CV from the About widget.
  # To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
  [[params.social]]
    icon = "cv"
    icon_pack = "ai"
    link = "Dongdong_Tian_CV.pdf"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "News"
  url = "#news"
  weight = 2

[[menu.main]]
  name = "Researches"
  url = "#researches"
  weight = 3

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 4

[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 5

[[menu.main]]
  name = "Resources"
  url = "#resources"
  weight = 6

[[menu.main]]
  name = "Services"
  url = "#services"
  weight = 7

[[menu.main]]
  name = "Awards"
  url = "#awards"
  weight = 8

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 9

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[menu.main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7

# Search.
[params.search]
  # Search provider:
  #   0: No search engine
  #   1: Built-in (Fuse)
  #   2: Algolia (https://www.algolia.com)
  engine = 1

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [params.search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"

# Uncomment the lines below to configure your website in a second language.
#[languages.zh]
#  languageCode = "zh-Hans"
#  title = "Chinese website title..."
#  [languages.zh.params]
#    name = "Your name in Chinese..."
#    role = "Your role in Chinese..."
#  [[languages.zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
